#!/usr/bin/env python3
"""Download Phosphor SVGs, build phosphor-lite.css, fetch Supabase UMD."""
from __future__ import annotations

import time

import re
import sys
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ICON_NAMES = ROOT / "tools" / "_icon_names.txt"
ICONS_DIR = ROOT / "vendor" / "icons"
CSS_PATH = ROOT / "css" / "phosphor-lite.css"
SUPABASE_DIR = ROOT / "vendor" / "supabase"
SUPABASE_PATH = SUPABASE_DIR / "supabase.js"

PHOSPHOR_BASE = "https://unpkg.com/@phosphor-icons/core@2.1.1/assets"
SUPABASE_URLS = [
    "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.49.1/dist/umd/supabase.js",
    "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/dist/umd/supabase.js",
]

UA = {"User-Agent": "CivicRadar-phosphor-lite/1.0"}


def parse_name(name: str) -> tuple[str, str]:
    """Return (weight, base) for a Phosphor class stem."""
    if name.endswith("-fill"):
        return "fill", name[: -len("-fill")]
    if name.endswith("-bold"):
        return "bold", name[: -len("-bold")]
    return "regular", name


def fetch(url: str, retries: int = 3) -> bytes | None:
    req = urllib.request.Request(url, headers=UA)
    last: Exception | None = None
    for attempt in range(retries):
        try:
            with urllib.request.urlopen(req, timeout=90) as resp:
                return resp.read()
        except urllib.error.HTTPError as e:
            if e.code == 404:
                return None
            last = e
        except urllib.error.URLError as e:
            last = e
        if attempt < retries - 1:
            time.sleep(1.5 * (attempt + 1))
    if last:
        raise last
    return None


def minify_svg(svg: str) -> str:
    svg = re.sub(r"<\?xml[^?]*\?>", "", svg)
    svg = re.sub(r"<!DOCTYPE[^>]*>", "", svg, flags=re.IGNORECASE)
    svg = re.sub(r"<!--.*?-->", "", svg, flags=re.DOTALL)
    svg = re.sub(r">\s+<", "><", svg)
    svg = re.sub(r"\s+", " ", svg)
    return svg.strip()


def svg_to_data_uri(svg_bytes: bytes) -> str:
    text = svg_bytes.decode("utf-8")
    mini = minify_svg(text)
    # Prefer currentColor for mask fills when Phosphor uses fill="black" etc.
    # Keep as-is for mask-image (color comes from background-color: currentColor).
    quoted = urllib.parse.quote(mini, safe="")
    return f'url("data:image/svg+xml,{quoted}")'


# Icons absent from Phosphor core - map class stem -> asset base name
FALLBACK_BASE = {
    "radar": "broadcast",
}


def download_icon(name: str) -> tuple[bool, str]:
    weight, base = parse_name(name)
    fb = FALLBACK_BASE.get(name) or FALLBACK_BASE.get(base)
    candidates = [
        f"{PHOSPHOR_BASE}/{weight}/{base}.svg",
        f"{PHOSPHOR_BASE}/regular/{name}.svg",
        f"{PHOSPHOR_BASE}/regular/{base}.svg",
    ]
    if fb:
        candidates.append(f"{PHOSPHOR_BASE}/{weight}/{fb}.svg")
        candidates.append(f"{PHOSPHOR_BASE}/regular/{fb}.svg")
    # Dedupe while preserving order
    seen: set[str] = set()
    urls: list[str] = []
    for u in candidates:
        if u not in seen:
            seen.add(u)
            urls.append(u)

    last_err = ""
    for url in urls:
        try:
            data = fetch(url)
        except Exception as e:
            last_err = f"{url}: {e}"
            print(f"  WARN {name}: {last_err}", file=sys.stderr)
            continue
        if data is None:
            last_err = f"404 {url}"
            continue
        out = ICONS_DIR / f"{name}.svg"
        out.write_bytes(data)
        return True, str(out)

    print(f"  FAIL {name}: {last_err or 'not found'}", file=sys.stderr)
    return False, last_err or "not found"


def build_css(ok_names: list[str], svg_map: dict[str, bytes]) -> str:
    lines = [
        "/* phosphor-lite - subset generated by tools/_build_phosphor_lite.py */",
        "i.ph, .ph {",
        "  display: inline-flex;",
        "  width: 1em;",
        "  height: 1em;",
        "  line-height: 1;",
        "  speak: never;",
        "  flex-shrink: 0;",
        "}",
        "",
    ]
    for name in ok_names:
        data_uri = svg_to_data_uri(svg_map[name])
        lines.append(f"i.ph.ph-{name}::before, .ph.ph-{name}::before {{")
        lines.append("  content: '';")
        lines.append("  display: block;")
        lines.append("  width: 1em;")
        lines.append("  height: 1em;")
        lines.append("  background-color: currentColor;")
        lines.append(f"  -webkit-mask-image: {data_uri};")
        lines.append(f"  mask-image: {data_uri};")
        lines.append("  -webkit-mask-size: contain;")
        lines.append("  mask-size: contain;")
        lines.append("  -webkit-mask-repeat: no-repeat;")
        lines.append("  mask-repeat: no-repeat;")
        lines.append("  -webkit-mask-position: center;")
        lines.append("  mask-position: center;")
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


def download_supabase() -> tuple[bool, int]:
    SUPABASE_DIR.mkdir(parents=True, exist_ok=True)
    for url in SUPABASE_URLS:
        print(f"Fetching Supabase: {url}")
        try:
            data = fetch(url)
        except Exception as e:
            print(f"  error: {e}", file=sys.stderr)
            continue
        if data is None:
            print("  404, trying next...")
            continue
        SUPABASE_PATH.write_bytes(data)
        return True, len(data)
    return False, 0


def main() -> int:
    names = [
        line.strip()
        for line in ICON_NAMES.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.strip().startswith("#")
    ]
    ICONS_DIR.mkdir(parents=True, exist_ok=True)
    CSS_PATH.parent.mkdir(parents=True, exist_ok=True)

    ok: list[str] = []
    fail: list[str] = []
    svg_map: dict[str, bytes] = {}

    print(f"Downloading {len(names)} Phosphor icons...")
    for name in names:
        success, _ = download_icon(name)
        if success:
            ok.append(name)
            svg_map[name] = (ICONS_DIR / f"{name}.svg").read_bytes()
            print(f"  OK  {name}")
        else:
            fail.append(name)

    css = build_css(ok, svg_map)
    CSS_PATH.write_text(css, encoding="utf-8")
    css_kb = CSS_PATH.stat().st_size / 1024

    sb_ok, sb_bytes = download_supabase()
    sb_kb = sb_bytes / 1024 if sb_ok else 0

    print()
    print("=== Summary ===")
    print(f"Icons: {len(ok)} ok / {len(fail)} fail (of {len(names)})")
    print(f"CSS:   {css_kb:.1f} KB -> {CSS_PATH}")
    if sb_ok:
        print(f"Supabase: {sb_kb:.1f} KB -> {SUPABASE_PATH}")
    else:
        print("Supabase: FAILED")
    if fail:
        print("Failed icons:")
        for n in fail:
            print(f"  - {n}")
    return 0 if len(ok) > 70 else 1


if __name__ == "__main__":
    raise SystemExit(main())
